Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis 
ant, cont, pox, aux: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 1
ant <- 0
pox <- 1
aux <- ant + pox

enquanto (aux <= 15 ) faca
         escreval(aux)
         ant <- ant + 1
         
         
fimenquanto


Fimalgoritmo