Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
num <- 2
cont <- 0
repita
      escreval(num," elevado a",cont," = ", (num ^ cont))
      
     cont <- cont + 1
ate ( cont > 10 )


Fimalgoritmo