Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

cont <- 2
repita
      escreval( cont, " elevado ao quadrado = ", (cont ^ 2))
      cont <- cont + 1
ate   ( cont > 20 )


Fimalgoritmo